'use strict'

module.exports = {
  data: {
    runs: {
      '1': {
        firstView: {
          'SpeedIndex': '',
          'TTFB': '',
          'URL': '',
          'adult_site': '',
          'aft': '',
          'base_page_cdn': '',
          'browser_main_memory_kb': '',
          'browser_name': '',
          'browser_other_private_memory_kb': '',
          'browser_process_count': '',
          'browser_version': '',
          'browser_working_set_kb': '',
          'bytesIn',
          'bytesInDoc': '',
          'bytesOut': '',
          'bytesOutDoc': '',
          'cached': '',
          'connections': '',
          'docCPUms': '',
          'docCPUpct': '',
          'docTime': '',
          'domContentLoadedEventEnd': '',
          'domContentLoadedEventStart': '',
          'domElements': '',
          'domInteractive': '',
          'domLoading': '',
          'domTime': '',
          'effectiveBps': '',
          'effectiveBpsDoc': '',
          'eventName': '',
          'firstPaint': '',
          'fixed_viewport': '',
          'fullyLoaded': '',
          'fullyLoadedCPUms': '',
          'fullyLoadedCPUpct': '',
          'gzip_savings': '',
          'gzip_total': '',
          'image_savings': '',
          'image_total': '',
          'isResponsive': '',
          'lastVisualChange': '',
          'loadEventEnd': '',
          'loadEventStart': '',
          'loadTime': '',
          'minify_savings': '',
          'minify_total': '',
          'numSteps': '',
          'optimization_checked': '',
          'pageSpeedVersion': '',
          'render': '',
          'requestsDoc': '',
          'requestsFull': '',
          'responses_200': '',
          'responses_404': '',
          'responses_other': '',
          'result': '',
          'run': '',
          'score_cache': '',
          'score_cdn': '',
          'score_combine': '',
          'score_compress': '',
          'score_cookies': '',
          'score_etags': '',
          'score_gzip': '',
          'score_keep-alive': '',
          'score_minify': '',
          'score_progressive_jpeg': '',
          'server_count': '',
          'server_rtt': '',
          'step': '',
          'tester': '',
          'title': '',
          'titleTime': '',
          'visualComplete': ''
        }
      }
    }
  }
};
